version: "3.8"

services:
  mongo:
    image: mongo:4.2
    container_name: "mongoDatabase"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB
    ports: 
      - "27017:27017"